export const DATE = {
  DATE_FORMAT: 'DD-MM-YYYY',
  DATE_FORMAT_V2: 'DD/MM/YYYY',
  DATE_FORMAT_V3: 'YYYY-MM-DD',
  DATE_FORMAT_V4: 'YYYYMMDD',

  DATE_FORMAT_DOT: 'YYYY.MM.DD',
  DATE_FORMAT_DOT_v2: 'DD.MM.YYYY',

  DATE_TIME_FORMAT: 'DD/MM/YYYY - HH:mm',
  DATE_TIME_FORMAT_V2: 'YYYY-MM-DD HH:mm',
  DATE_TIME_FORMAT_V3: 'YYYY-MM-DD HH:mm:ss',
  DATE_TIME_FORMAT_V4: 'YYYY.MM.DD HH:mm:ss',

  TIME_DATE_FORMAT: 'HH:mm DD/MM/YYYY',
  TIME_DATE_FORMAT_V2: 'HH:mm YYYY-MM-DD',

  TIME_FORMAT: 'HH:mm',
  DATE_TIME_FORMAT_FULL: 'HH:mm:ss',
  YEAR_MONTH_FORMAT: 'YYYY-MM'
} as const
